### PR TITLE
Fix security group not restored

### LINKED ISSUE #369: Security Group not restored on VMs when removed outside of terraform
### Terraform Version

```
$ terraform version
Terraform v1.4.5
on linux_amd64
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/outscale/outscale v0.9.1
+ provider registry.terraform.io/ovh/ovh v0.30.0

Your version of Terraform is out of date! The latest version
is 1.5.3. You can update by downloading from https://www.terraform.io/downloads.html
```

### Terraform Configuration Files

```terraform

resource "outscale_vm" "vm" {

  image_id           = var.image_id
  vm_type            = var.vm_type
  keypair_name       = var.ssh_keypair_name
  security_group_ids = ["${outscale_security_group.sg_kafka_nodes.id}","${data.outscale_security_group.sg_allow_ssh_from_jumphosts.id}"]
  subnet_id          = var.subnet_id

  placement_tenancy     = "default"
  nested_virtualization = false

  #user_data             = data.template_cloudinit_config.cloudinit.rendered

  dynamic "tags" {
    for_each = merge(local.vm_tags,var.tags)
    content {
      key           = tags.key
      value         = tags.value
    }
  }

  #AML - switch rootdisk to 50G and SSD
  block_device_mappings {
    device_name = "/dev/sda1"     # /dev/sda1 corresponds to the root device of the VM
    bsu {
      volume_size = var.root_volume_size
      volume_type = var.root_volume_type
      delete_on_vm_deletion = true
    }
  }

  lifecycle {
    ignore_changes = [
      user_data
    ]
  }
}
resource "outscale_security_group" "sg_kafka_nodes" {
  security_group_name = "secgroup-kafka"
  description = "kafka node security group"
  net_id      = data.outscale_net.vpc_poc_mdw.net_id
}
data "outscale_net" "vpc_poc_mdw" {
  filter {
      name   = "tag_values"
      values = ["vpc_poc_mdw${var.infra_env_suffix}"]
  }
}
# Retreive existing security group of jumphost to be member of to allow communication
data "outscale_security_group" "sg_allow_ssh_from_jumphosts" {
  filter {
      name   = "security_group_names"
      values = ["sg_allow_ssh_from_jumphosts"]
  }
}

```

### Expected Behavior

1. VM ressource is generated with two security groups ID.
2. Outside of terraform, with osc-cli, we reduce the number of Security Group to one.
3. Then, a`terraform apply` should update the security groups attached to the VM, but the "lost" security group is not detected / reaffected to the VM.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply`
3. `osc-cli api UpdateVm --profile ${OSC_PROFILE}  --VmId "${vmid}" --SecurityGroupIds "[\"${VM_SG_TO_KEEP}\"]"`
4. `terraform apply` is detecting no change

### PR DESCRIPTION
**Pull request by outscale-toa**
Fixed #369

### CODE REVIEW

File: outscale/resource_outscale_vm.go [hunk 1]
```diff
@@ -667,6 +667,11 @@ func resourceOAPIVMRead(d *schema.ResourceData, meta interface{}) error {
 		if err := d.Set("admin_password", adminPassword); err != nil {
 			return err
 		}
+		if sgids := utils.SetToStringSlice(d.Get("security_group_ids").(*schema.Set)); len(sgids) > 0 {
```
Comment (outscale-mgo) [inline outscale/resource_outscale_vm.go:670]: Maybe you could simplify this using:
```go
if len(utils.SetToStringSlice(d.Get("security_group_ids").(*schema.Set))) > 0 {
...
```

File: outscale/resource_outscale_vm.go [hunk 2]
```diff
@@ -976,7 +981,7 @@ func buildCreateVmsRequest(d *schema.ResourceData, meta interface{}) (oscgo.Crea
 		request.SetPrivateIps(privateIPs)
 	}
 
-	if sgIDs := utils.InterfaceSliceToStringSlice(d.Get("security_group_ids").([]interface{})); len(sgIDs) > 0 {
+	if sgIDs := utils.SetToStringSlice(d.Get("security_group_ids").(*schema.Set)); len(sgIDs) > 0 {
```
Comment (outscale-mgo) [inline outscale/resource_outscale_vm.go:984]: same here ?

Comment (outscale-toa) [reply outscale/resource_outscale_vm.go:984]: I need ``` sgIDs ```  in  ``` request.SetSecurityGroupIds(sgIDs) ```

**Review by outscale-mgo — APPROVED** [review]
