### PR TITLE
Fix net_peering mandatory "accepter_owner_id" parameter.

### LINKED ISSUE #497: vpc peering / net peering
---
name: Bug report
about: deployment of a net peering connection no longer works
labels: bug, new

---

### Terraform Version
```bash
 › terraform version
Terraform v1.10.3
on linux_amd64
+ provider registry.terraform.io/outscale/outscale v1.0.0
```

### Terraform Configuration Files

```terraform
terraform {
  required_providers {
    outscale = {
      source  = "outscale/outscale"
      version = "1.0.0"
    }
  }
}

# Variables pour le compte 1
variable "access_key_id_account1" {}
variable "secret_key_id_account1" {}
variable "region_account1" {}

# Variables pour le compte 2
variable "access_key_id_account2" {}
variable "secret_key_id_account2" {}
variable "region_account2" {}

# Provider pour le compte 1
provider "outscale" {
  alias         = "account1"
  access_key_id = var.access_key_id_account1
  secret_key_id = var.secret_key_id_account1
  region        = var.region_account1
}

# Provider pour le compte 2
provider "outscale" {
  alias         = "account2"
  access_key_id = var.access_key_id_account2
  secret_key_id = var.secret_key_id_account2
  region        = var.region_account2
}

# VPC dans le compte 1
resource "outscale_net" "vpc_account1" {
  provider  = outscale.account1
  ip_range  = "10.0.0.0/16"
}

# VPC dans le compte 2
resource "outscale_net" "vpc_account2" {
  provider  = outscale.account2
  ip_range  = "192.168.0.0/16"
}

# Création du Net Peering du côté du compte 1 (source)
resource "outscale_net_peering" "peering_account1" {
  provider        = outscale.account1
  source_net_id   = outscale_net.vpc_account1.net_id
  accepter_net_id = outscale_net.vpc_account2.net_id
}

# Acceptation du peering du côté du compte 2
resource "outscale_net_peering_acceptation" "peering_acceptation" {
  provider       = outscale.account2
  net_peering_id = outscale_net_peering.peering_account1.net_peering_id
}
```

### Debug Output
```
outscale_net_peering tf_mux_provider="*schema.GRPCProviderServer" timestamp="2025-01-17T11:55:52.787+0100"
2025-01-17T11:55:52.788+0100 [DEBUG] provider.terraform-provider-outscale_v1.0.0: 2025/01/17 11:55:52 [DEBUG] VPC Peering Create options: osc.CreateNetPeeringRequest{AccepterNetId:"vpc-c2b2d7c1", AccepterOwnerId:(*string)(nil), DryRun:(*bool)(nil), SourceNetId:"vpc-1a93637b"}
```
>>> AccepterOwnerId:(*string)(nil) doit contenir l'id du compte cible

### References
Behavior of CreateNetPeering (OUTSCALE API)

In the previous TINA OS update, the AccepterOwnerId parameter was added to the [CreateNetPeering](https://docs.outscale.com/api.html#createnetpeering) OUTSCALE API method as optional.

From this update, in the case of sharing a Net peering connection between two Nets belonging to two different users, the AccepterOwnerId parameter is now mandatory.

### PR DESCRIPTION
**Pull request by outscale-toa**
Closed #497

### CODE REVIEW

File: outscale/resource_outscale_net_peering.go [hunk 1]
```diff
@@ -99,10 +104,9 @@ func ResourceOutscaleLinPeeringCreate(d *schema.ResourceData, meta interface{})
 		return nil
 	})
 
-	var errString string
 	if err != nil {
-		errString = err.Error()
-		return fmt.Errorf("Error creating Net Peering. Details: %s", errString)
+		netErr := "Error creating Net Peering. Details:" + err.Error()
+		return errors.New(netErr)
```
Comment (jfbus) [inline outscale/resource_outscale_net_peering.go:109]: You should wrap the error : `fmt.Errorf("Error creating Net Peering: %w", err)`

**Review by jfbus — APPROVED** [review]
